springdoc:
  api-docs:
    path=/api-docs:
server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:file:./data_base
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update